language: perl
perl:
    - "5.24"
#    - "5.26"
    - "5.28"
    - "dev"
matrix:
    include:
        - perl: 5.26
          env: COVERAGE=1   # enables coverage+coveralls reporting
    allow_failures:
        - perl: dev
sudo: false
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - cpan-install Code::TidyAll::Plugin::PerlCritic Perl::Critic
    - build-dist
    - cd $BUILD_DIR
install:
    - cpan-install --deps       # installs prereqs, including recommends
    - cpan-install --coverage   # installs converage prereqs, if enabled
before_script:
    - coverage-setup
script:
    - prove -l -j$(test-jobs) $(test-files)   # parallel testing
after_success:
    - coverage-report
notifications:
    email:
        on_success: never
        on_failure: always